### PR TITLE
Support for Flutter 1.6.0 (new error formats)

### LINKED ISSUE #24: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'. -  Flutter 1.5.9
```
file:///Users/calvinmuller/.pub-cache/hosted/pub.dartlang.org/flutter_sticky_header-0.3.4/lib/src/widgets/sticky_header_layout_builder.dart:147:16: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/calvinmuller/iStreet/Mobile/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
      context: context);
               ^
```

### PR DESCRIPTION
**Pull request by ened**
fixes #24

### CODE REVIEW

**Comment by cimplesid** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'SliverHitTestResult' is not a subtype of type 'BoxHitTestResult'
E/flutter (28410): #0      RenderSliverStickyHeader.hitTestChildren 
package:flutter_sticky_header/…/rendering/sliver_sticky_header.dart:273
after following your steps i m getting issue hile taping on stick header

**Comment by ened** [comment]
@cimplesid Updated the PR, please update your local copy and confirm errors are gone & functionality retained. Thx.

**Comment by cimplesid** [comment]
> @cimplesid Updated the PR, please update your local copy and confirm errors are gone & functionality retained. Thx.

500% working thankyou @ened

**Comment by ened** [comment]
@cimplesid hi - ok to merge & publish?

**Comment by cimplesid** [comment]
> @letsar hi - ok to merge & publish?

ened can u look into another plugin called admob flutter it have issue in platform view and they are looking for maintainer for the project and i need that plugin asap problem with it is if it is implemented
in project then an edit on project dont work even after commenting the code so if u have time kindly look into it and @letsar merge the PR

**Comment by letsar** [comment]
Thanks, I'll look at it

**Comment by ened** [comment]
@letsar could you cut a new major release to pub?

**Comment by ened** [comment]
@letsar let's get a new release on pub?

**Pull request merged**
