### PR TITLE
Fixing SliverStickyHeaderState cast error due to null-safety migration

### PR DESCRIPTION
**Pull request by amitkot**
Solves #62 

@letsar please review, thanks!

### CODE REVIEW

**Comment by StorminGorman** [comment]
Is development on this halted?  I'm tempted to just add a git dep to your PR fork .....

**Comment by amitkot** [comment]
That what I did for now.
@letsar would it be possible to merge this? I am currently using it in production on Android and iOS (https://bringitapp.co).

**Comment by ThexXTURBOXx** [comment]
For the time being just use
```yaml
dependency_overrides:
  flutter_sticky_header:
    git:
      url: https://github.com/amitkot/flutter_sticky_header.git
      ref: master
```

**Comment by oscarshaitan** [comment]
this should be merged months ago!!!!

**Comment by timcreatedit** [comment]
@letsar Pleeeease merge this pull request, it should be really quick and returns this great package to being usable

**Comment by oscarshaitan** [comment]
I get tired and create my own widgets with the help of Sliver_tools check that  
https://pub.dev/packages/sliver_tools

**Comment by letsar** [comment]
Thank you a lot, I merged it and published a 0.6.1 version on pub

**Pull request merged**
